### ISSUE TITLE
Edge table crashes on sorting of comments in newest dev

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#265] opened 2023-05-30 07:53 UTC
View nodes table, sort by comments. It works.
Switch to edge table, sort by comments. It does not.

Note the TypeError error in this image as that appears in both local and DO runs. The web socket issue is only on DO and will be reported separately. It appears unrelated since that error does not appear on local runs.

<img width="865" alt="Screenshot 2023-05-30 at 3 49 28 AM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/a32514b4-af87-432d-8b24-359eef13a93e">

**Comment by benloh** [comment] 2023-05-30 16:30
I did see errors like this while developing.  But generally quitting the server and restarting would fix the problem.  Some of the server code is not auto-restarted with code changes (pulls).  Try that first?  (Sorting by comments on edge table works for me)

**Comment by jdanish** [comment] 2023-05-30 16:36
Ok I’ll re-try and report back this afternoon thanks.

**Comment by jdanish** [comment] 2023-05-30 19:02
Tried with running classroom, and it seems fine otherwise. Different error now from running locally, so re-posting.

Anything else I should try?

<img width="1712" alt="Screenshot 2023-05-30 at 3 02 05 PM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/35fbfd26-3bcf-42b2-a0dd-128b0dd15073">

**Comment by jdanish** [comment] 2023-05-30 20:23
OK, in case this helps: my new network (testing) I created by using ./nc.js with a new dataset name. Everything else works find. Comments still crashed. I added text to both comments. Now they sort fine. Could to be related to the issue where comments are not initially set correctly when empty, but only in the edge table? @benloh

**Comment by benloh** [comment] 2023-05-30 20:49
Oh did you ever update your `_default.template.toml` file?  
But yeah, you might be onto something.  I'll see if I can reproduce it.

**Comment by jdanish** [comment] 2023-05-30 20:58
Oh, no I just tried and get this error. 

<img width="877" alt="Screenshot 2023-05-30 at 4 59 31 PM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/4ca8be9f-4683-44c6-aa99-3d31dbf372f2">

Other ideas?  Also, I am not sure how likely it is anyone will remember to run ncRegenerateDefaultTemplate() so we might want a long-term alternative solution?

**Comment by benloh** [comment] 2023-05-30 21:07
`ncRegenerateDefaultTemplate` was intended really only for developers and it only needs to be run when `template-schema.js` is changed.  When we're done with this my plan was to commit and push `_default.template.toml` so this shouldn't be an issue in the future.

As for your error, check `nc-logic.js:1228` -- there should be a `JSCLI.AddFunction` call with `function ncRegenerateDefaultTemplate` on the next line.  Any chance you hadn't quit and restarted the server?

**Comment by jdanish** [comment] 2023-05-31 00:48
OK, the issue was it only works if you do npm run dev, so I have done that. Seems it worked!  And the problem is resolved.

**Comment by benloh** [comment] 2023-05-31 01:50
Closing.  All issues addressed.

**Closed as completed by benloh** 2023-05-31 01:50 UTC
