### ISSUE TITLE
Clicking on node locks edges?

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#230] opened 2022-03-21 19:54 UTC
In the most recent build, if I click on a node (not even to edit, just select it), the edges all lock and won't unlock. I see a host of "Edit lock" messages in the console when this happens as well.

**Comment by benloh** [comment] 2022-03-21 21:01
@jdanish I can't reproduce this either.  Please send me the problem data files.

**Comment by jdanish** [comment] 2022-03-21 21:03
Here you go. This is what I have been testing with since we are going to use it in an upcoming study. I will try and remember to test future things with other data files just in case it is a bad file, though.

[VFOI.zip](https://github.com/netcreateorg/netcreate-2018/files/8319229/VFOI.zip)

**Comment by benloh** [comment] 2022-03-21 21:08
Thanks.  Hmm...I still can't reproduce.  You probably already did this, but can you ctrl-c, do a pull, and run it again, just to make sure we're starting fresh?

**Comment by jdanish** [comment] 2022-03-21 22:47
I tried the following and still see the issue:

1. clear cache in chrome
2. update to newest chrome
3. nvm use just in case gem-step screwed me up
4. npm ci
5. Try with a new database (create from scratch)

No luck.

Note, I should clarify that if you click on a node and then the edge it is still editable. But the edges table is faded and acts as if it is disabled or filtered out - clicking on the nodes doesn't work.

<img width="1665" alt="Screen Shot 2022-03-21 at 6 46 30 PM" src="https://user-images.githubusercontent.com/5529898/159375389-09128e8f-dc5f-460b-92d8-201c0578d0ac.png">

**Comment by jdanish** [comment] 2022-03-21 22:48
Note this bug apparently goes back a while - you can see it on my server which is a few days behind: 

http://167.71.174.206/graph/VFOI1/#/edit/C1-P1-7DG?admin=true

**Comment by benloh** [comment] 2022-03-21 22:55
Oh.  Edges are not locked.  That locked message was a debug message that I committed by accident.

The fading is #197 and should be fixed by #199 once I implement it.

Closing.

**Closed by benloh** 2022-03-21 22:55 UTC

**Comment by jdanish** [comment] 2022-03-21 23:03
Ahh, sorry!!

----
(from my iPhone)

Joshua Danish
http://www.joshuadanish.com
